name: flutter_disposebag
description: Automatically disposes StreamSubscription and closes Sink when disposing State<T>.
version: 1.1.0
homepage: https://github.com/Flutter-Dart-Open-Source/flutter_disposebag.git
repository: https://github.com/Flutter-Dart-Open-Source/flutter_disposebag.git
issue_tracker: https://github.com/Flutter-Dart-Open-Source/flutter_disposebag/issues

environment:
  sdk: '<4.0.0'

dependencies:
  meta: ^1.3.0
  disposebag: ^1.5.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
